export const TYPES = {
CARGAR_PRODUCTOS:"CARGAR_PRODUCTOS",
AÑADIR_A_CANASTA : "AÑADIR_A_CANASTA",
BORRAR_UNO_CANASTA : "BORRAR_UNO_CANASTA",
BORRAR_TODOS_CANASTA : "BORRAR_TODOS_CANASTA",
BORRAR_CANASTA : "BORRAR_CANASTA",
ENVIAR_PEDIDO:"ENVIAR_PEDIDO",
};