
export const CARGAR_PRODUCTOS= "CARGAR_PRODUCTOS"
export const AÑADIR_A_CANASTA= "AÑADIR_A_CANASTA"
export const BORRAR_UNO_CANASTA= "BORRAR_UNO_CANASTA"
export const BORRAR_TODOS_CANASTA= "BORRAR_TODOS_CANASTA"
export const BORRAR_CANASTA= "BORRAR_CANASTA"
export const ENVIAR_PEDIDO= "ENVIAR_PEDIDO"
export const CALCULAR_TOTAL= "CALCULAR_TOTAL"
